recipe/meta.yaml

Update to recipe for 3.21.7 mistakenly `py-lief  # [not (win and py2k)]` to `py-lief  # [not win]` when removing py2.7-related cruft. This only requires a re-build for Windows; the Linux and macOS builds should be fine.

Fix py-lief being dropped as dependency on Windows

---

recipe/meta.yaml

Bumps version for conda-build 3.22.0 release.
#17 used my fork and didn't appear to trigger Prefect workflows, trying without fork.

Bump version to 3.22.0

---

recipe/meta.yaml

Removes glob2 per https://github.com/conda/conda-build/pull/5005 and updates minimum conda dependency.
Xref https://github.com/conda/conda-build/issues/5011

Bump to 3.27.0

---

recipe/meta.yaml

- Remove unnecessary `six` package
- Sorts dependencies to mirror conda-build and conda-forge's recipes for easier maintenance
- Bump to latest version and update dependencies

Bump to 3.28.0

---

recipe/meta.yaml

conda-build 3.28.2
- [PKG-3688](https://anaconda.atlassian.net/browse/PKG-3688) 
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/3.28.2)
- n/a
- Corrects several regressions in conda-build 3.28.0
[PKG-3688]: https://anaconda.atlassian.net/browse/PKG-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump to 3.28.2

---

recipe/meta.yaml

conda-build 3.28.3
- [PKG-3745](https://anaconda.atlassian.net/browse/PKG-3745) 
- [Upstream repository](github.com/conda/conda-build)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/3.28.3)
- n/a
- Bump to newest version
[PKG-3745]: https://anaconda.atlassian.net/browse/PKG-3745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

conda-build v3.28.3

---

abs.yaml

We forgot to build for python 3.12 in https://github.com/AnacondaRecipes/conda-build-feedstock/pull/38.

Build with python 3.12

---

recipe/meta.yaml

conda-build 24.3.0
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.3.0)
- https://github.com/conda/conda-build/issues/5204

Bump to 24.3.0

---

recipe/meta.yaml
recipe/test_bdist_conda_setup.py

conda-build 24.5.0
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.5.0)
- Relevant dependency PRs/issues:
- https://github.com/conda/conda-build/pull/5299
- https://github.com/conda/conda-build/issues/5204

Bump to 24.5.0

---

recipe/meta.yaml

conda-build 24.5.0
Fix bad sha from https://github.com/AnacondaRecipes/conda-build-feedstock/pull/43

Fix sha256

---

recipe/meta.yaml

🚧 _Please do not merge before Tuesday, May 28th_ 🚧
conda-build 24.5.1
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.5.1)
- https://github.com/conda/conda-build/issues/5319
- Relevant dependency PRs/issues:
- https://github.com/conda/conda-build/issues/5342
- https://github.com/conda/conda-build/issues/5267

Bump conda-build version to 24.5.1

---

recipe/meta.yaml

conda-build 24.7.1
- [PKG-5428](https://anaconda.atlassian.net/browse/PKG-5428) 
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.7.1)
- n/a
- https://github.com/conda/conda-build/issues/5381
- https://github.com/conda/conda-build/issues/5433
[PKG-5428]: https://anaconda.atlassian.net/browse/PKG-5428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump conda-build version to 24.7.1

---

recipe/meta.yaml

- [PKG-5748](https://anaconda.atlassian.net/browse/PKG-5748)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.9.0)
- n/a
- https://github.com/conda/conda-build/issues/5481
[PKG-5748]: https://anaconda.atlassian.net/browse/PKG-5748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump conda-build to version 24.9.0

---

recipe/meta.yaml

- [PKG-5748](https://anaconda.atlassian.net/browse/PKG-5748)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.11.1)
- https://github.com/conda/conda-build/pull/5550
- https://github.com/conda/conda-build/issues/5524
[PKG-5748]: https://anaconda.atlassian.net/browse/PKG-5748

Bump conda-build version to 24.11.1

---

recipe/meta.yaml

conda-build 24.11.2
- [PKG-6329](https://anaconda.atlassian.net/browse/PKG-6329) 
- [Upstream repository](https://github.com/conda/conda-build/issues/5524)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/24.11.2)
- n/a
- patch resolving https://github.com/conda/conda-build/issues/5416
[PKG-6329]: https://anaconda.atlassian.net/browse/PKG-6329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump to 24.11.2

---

recipe/meta.yaml

conda-build 25.1.1
- [PKG-6766](https://anaconda.atlassian.net/browse/PKG-6766) 
- [Upstream repository](http://github.com/conda/conda-build)
- [Upstream changelog/diff](https://github.com/conda/conda-build/compare/24.11.2...25.1.1)
This includes the unreleased 25.1.0, which had some deprecations not removed and triggered deprecation exceptions for users
[PKG-6766]: https://anaconda.atlassian.net/browse/PKG-6766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump to 25.1.1.

---

recipe/meta.yaml

conda-build 25.1.2
Destination channel: defaults
- [PKG-7015](https://anaconda.atlassian.net/browse/PKG-7015) 
- [Upstream repository](https://github.com/conda/conda-build/issues/5524)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/25.1.2)
- n/a
- ...
[PKG-7015]: https://anaconda.atlassian.net/browse/PKG-7015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump version to 25.1.2

---

recipe/meta.yaml

conda-build 25.3.0
- [PKG-7430](https://anaconda.atlassian.net/browse/PKG-7430)
- [Upstream repository](https://github.com/conda/conda-build/issues/5632)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/25.3.0)
- n/a
- Latest version of `conda-build`
[PKG-7430]: https://anaconda.atlassian.net/browse/PKG-7430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

conda-build 25.3.0

---

recipe/meta.yaml

conda-build 25.3.2
- [PKG-7865](https://anaconda.atlassian.net/browse/PKG-7865)
- [Upstream repository](https://github.com/conda/conda-build/issues/5632)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/25.3.2)
- n/a
- Patch release to correct regressions in `conda-build 25.3.0`
[PKG-7865]: https://anaconda.atlassian.net/browse/PKG-7865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

conda-build 25.3.2

---

recipe/meta.yaml

conda-build 25.4.2
- [PKG-8027](https://anaconda.atlassian.net/browse/PKG-8027) 
- [Upstream repository](https://github.com/conda/conda-build/issues/5670)
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/25.4.2)
- n/a
- April release with security patches
[PKG-8027]: https://anaconda.atlassian.net/browse/PKG-8027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

conda-build 25.4.2

---

recipe/meta.yaml

conda-build 25.5.0
- [Upstream changelog/diff](https://github.com/conda/conda-build/releases/tag/25.5.0)
- This is the regularly scheduled May, 2025 release of conda-build.

conda-build 25.5.0
